### ISSUE TITLE
Task in PENDING state on Windows

### ISSUE THREAD

**Issue by jeisonjei** [eeintech/django-celery-progress-demo#4]
Hello, thank you for this example,
just a note about running celery on Windows - maybe it will be useful for someone:
to avoid tasks always hanging on in PENDING state, need to assign flag
--pools=solo
original post is here
https://stackoverflow.com/a/26641208/12613870

**Comment by eeintech** [comment]
Thanks @jeisonjei, is this issue only on Windows?

**Comment by jeisonjei** [comment]
Yes, as I know only on Windows
